const {JSDOM}=require('jsdom');
const fs=require('fs');
const assert=require('node:assert/strict');
(async()=>{
 const base=process.env.BOARDSCOPE_TEST_URL||'http://127.0.0.1:8000';
 let html;for(let i=0;i<50;i++){try{html=await (await fetch(base)).text();break}catch(e){await new Promise(r=>setTimeout(r,100))}}if(!html)throw Error('Server unavailable');
 const dom=new JSDOM(html,{url:base,runScripts:'outside-only',pretendToBeVisual:true});
 const w=dom.window,d=w.document,errors=[];
 w.fetch=(url,args)=>fetch(new URL(url,base),args);
 w.HTMLDialogElement.prototype.showModal=function(){this.open=true};
 w.HTMLDialogElement.prototype.close=function(){this.open=false};
 w.addEventListener('error',e=>errors.push(e.message));
 w.eval(fs.readFileSync(require('node:path').join(__dirname,'../boardscope/static/app.js'),'utf8'));
 const q=s=>d.querySelector(s);
 async function wait(fn){for(let i=0;i<150;i++){if(fn())return;await new Promise(r=>setTimeout(r,50))}throw Error('UI wait failed. '+d.body.textContent.slice(-1800));}
 await wait(()=>d.querySelectorAll('.board').length===2);
 assert(d.body.textContent.includes('AI model not configured'));
 async function run(env,policy){q('#new-run').click();let form=q('#form');const board=[...form.elements.board_id.options].find(o=>o.textContent.includes(env));form.elements.board_id.value=board.value;form.elements.test.value='reboot';form.elements.cycles.value=4;form.elements.interval_s.value=0;form.elements.failure_policy.value=policy;form.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await wait(()=>!q('#dialog').open);}
 await run('Ubuntu','continue');
 await wait(()=>q('.run-summary .row.spread > span')?.textContent==='completed');
 assert(q('#content').textContent.includes('4 / 4 cycles'));
 assert(q('#content').textContent.includes('SIMULATED'));
 q('#back').click();
 await run('Yocto','pause');
 await wait(()=>q('[data-control="resume"]'));
 assert(q('#content').textContent.includes('expected 3 / observed 2'));
 q('#investigate').click();
 await wait(()=>q('#content').textContent.includes('Evidence comparison · AI not configured'));
 assert(q('#content').textContent.includes('expected 3, observed 2'));
 q('[data-control="resume"]').click();
 await wait(()=>q('.run-summary .row.spread > span')?.textContent==='completed');
 q('#back').click();q('[data-nav="tests"]').click();q('[data-add-script]').click();
 q('#form').elements.name.value='Reviewed test';q('#form').elements.source.value='true';q('#form').elements.confirmed.checked=true;
 q('#form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
 await wait(()=>!q('#dialog').open);assert(q('#content').textContent.includes('Reviewed test'));
 q('[data-nav="boards"]').click();q('[data-add-board]').click();
 const f=q('#form');f.elements.name.value='<img src=x onerror=alert(1)>';f.elements.mode.value='simulator';f.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
 await wait(()=>!q('#dialog').open);assert(q('#content').textContent.includes('<img src=x onerror=alert(1)>'));assert(!q('#content img'));
 q('[data-add-board]').click();
 const sf=q('#form');sf.elements.name.value='Desk password board';sf.elements.mode.value='ssh';sf.elements.host.value='192.0.2.123';sf.elements.username.value='engineer';sf.elements.auth_method.value='password';sf.elements.ssh_password.value='fake-ui-session-password';
 sf.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
 await wait(()=>!q('#dialog').open);
 const physical=[...d.querySelectorAll('.board')].find(x=>x.textContent.includes('Desk password board'));
 assert(physical);assert(!physical.textContent.includes('fake-ui-session-password'));
 physical.querySelector('[data-connect]').click();
 assert.equal(q('#form').elements.auth_method.value,'password');assert.equal(q('#form').elements.ssh_password.value,'');assert(q('#check-ssh')&&q('#check-uart'));
 q('#form').elements.host.value='192.0.2.124';q('#form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await wait(()=>!q('#dialog').open);
 assert(q('#content').textContent.includes('192.0.2.124'));
 const edited=[...d.querySelectorAll('.board')].find(x=>x.textContent.includes('Desk password board'));edited.querySelector('[data-connect]').click();q('#forget-passwords').click();await wait(()=>q('#form-error').textContent==='Session passwords forgotten.');q('#cancel').click();
 q('[data-add-board]').click();
 const uf=q('#form');uf.elements.name.value='UART desk board';uf.elements.mode.value='uart';uf.elements.serial_port.value='/dev/boardscope-nonexistent-test';uf.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await wait(()=>!q('#dialog').open);
 const uartCard=[...d.querySelectorAll('.board')].find(x=>x.textContent.includes('UART desk board'));assert(uartCard);assert(uartCard.textContent.includes('UART'));assert(uartCard.querySelector('[data-start]'));
 uartCard.querySelector('[data-start]').click();const ur=q('#form');assert.equal(ur.elements.transport.value,'uart');assert.equal(ur.elements.test.value,'inventory');assert([...ur.elements.test.options].filter(o=>o.value!=='inventory').every(o=>o.disabled));assert(q('#transport-note').textContent.includes('SSH is not contacted'));
 ur.elements.cycles.value=1;ur.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await wait(()=>!q('#dialog').open);await wait(()=>q('.run-summary .row.spread > span')?.textContent==='completed');assert(q('#content').textContent.includes('UART'));assert(q('#content').textContent.includes('Cannot open serial port'));assert(q('#content').textContent.includes('UART: Started inventory'));
 assert.equal(errors.length,0,errors.join('\n'));
 console.log('Dashboard live-service DOM checks passed: passing reboot, failure/pause, comparison, resume, custom script registration, board registration and escaping.');
 dom.window.close();
})().catch(e=>{console.error(e);process.exit(1)});
